# WARNING!
# This is a development version of THE Bigcapital docker-compose.yml file.
# Avoid using this file in your production environment.
# We're exposing here sensitive ports and mounting code volumes for rapid development and debugging of the server stack.

version: '3.3'

services:
  mariadb:
    build:
      context: ./docker/mariadb
    environment:
      - MYSQL_DATABASE=${SYSTEM_DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    volumes:
      - mysql:/var/lib/mysql
    expose:
      - '3306'
    ports:
      - '3306:3306'
    deploy:
      restart_policy:
        condition: unless-stopped

  redis:
    build:
      context: ./docker/redis
    expose:
      - '6379'
    ports:
      - '6379:6379'
    volumes:
      - redis:/data
    deploy:
      restart_policy:
        condition: unless-stopped

  gotenberg:
    image: gotenberg/gotenberg:7
    ports:
      - '9000:3000'

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    ports:
      - '9002:9000'
      - '9001:9001'
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio:/data
    deploy:
      restart_policy:
        condition: unless-stopped

  mc:
    image: minio/mc:latest
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc alias set myminio http://minio:9000 minioadmin minioadmin) do echo '...waiting...' && sleep 1; done;
      /usr/bin/mc mb myminio/bigcapital;
      /usr/bin/mc anonymous set public myminio/bigcapital;
      echo 'MinIO bucket ready';
      tail -f /dev/null;
      "
  mailpit:
    image: axllent/mailpit:latest
    container_name: bigcapital-mailpit
    restart: unless-stopped
    ports:
      - "1025:1025"   # SMTP
      - "8025:8025"   # Web UI
    volumes:
      - mailpit-data:/data
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
# Volumes
volumes:
  mysql:
    name: bigcapital_dev_mysql
    driver: local

  redis:
    name: bigcapital_dev_redis
    driver: local

  minio:
    name: bigcapital_dev_minio
    driver: local
  mailpit-data:
    name: bigcapital_dev_mailpit
    driver: local
